name: covid19_dashboard
description: A flutter application showing the latest statistics about Covid19

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+3
  path_provider: ^1.6.5
  provider: ^4.0.4
  page_view_indicators: ^1.2.0
  flutter_linkify: ^2.1.0
  url_launcher: ^5.2.5
  connectivity: ^0.4.8+2
  flutter_svg: ^0.15.0
  intl: ^0.16.0
  share: ^0.6.3+5
  package_info: ^0.4.0+13
  google_maps_flutter: ^0.5.25
  syncfusion_flutter_core: ^18.1.36
  syncfusion_flutter_charts: ^18.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

