name: covid19_dashboard
description: A flutter application showing the latest statistics about Covid19

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+3
  path_provider: ^1.5.1
  provider: ^2.0.0
  page_view_indicators: ^1.2.0
  flutter_linkify: ^2.1.0
  url_launcher: ^5.2.5
  connectivity: ^0.4.5+3
  flutter_svg: ^0.15.0
  intl: ^0.16.0
  share: ^0.6.3+5
  package_info: ^0.4.0+13
  google_maps_flutter: ^0.5.21+15
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

