name: covid19_dashboard
description: A flutter application showing the latest statistics about Covid19

version: 1.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+3
  path_provider: ^1.6.5
  provider: ^4.0.4
  connectivity: ^0.4.8+2
  google_maps_flutter: ^0.5.25
  syncfusion_flutter_core: ^18.1.36
  syncfusion_flutter_charts: ^18.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

